var annotated_dup =
[
    [ "ButtonWidget", "class_button_widget.html", "class_button_widget" ],
    [ "CheckBoxWidget", "class_check_box_widget.html", "class_check_box_widget" ],
    [ "ColorEngine", "class_color_engine.html", "class_color_engine" ],
    [ "colorRGBA", "structcolor_r_g_b_a.html", "structcolor_r_g_b_a" ],
    [ "CommuterWidget", "class_commuter_widget.html", "class_commuter_widget" ],
    [ "ContainerHWidget", "class_container_h_widget.html", "class_container_h_widget" ],
    [ "ContainerVWidget", "class_container_v_widget.html", "class_container_v_widget" ],
    [ "CursorTask", "class_cursor_task.html", "class_cursor_task" ],
    [ "DesktopFeatures", "struct_desktop_features.html", "struct_desktop_features" ],
    [ "DesktopWidget", "class_desktop_widget.html", "class_desktop_widget" ],
    [ "FontChar", "struct_font_char.html", "struct_font_char" ],
    [ "FontData", "struct_font_data.html", "struct_font_data" ],
    [ "FontEngine", "class_font_engine.html", "class_font_engine" ],
    [ "FrameWidget", "class_frame_widget.html", "class_frame_widget" ],
    [ "InputWidget", "class_input_widget.html", "class_input_widget" ],
    [ "KeyboardTask", "class_keyboard_task.html", "class_keyboard_task" ],
    [ "LabelWidget", "class_label_widget.html", "class_label_widget" ],
    [ "MiniButtonWidget", "class_mini_button_widget.html", "class_mini_button_widget" ],
    [ "ProgressBarWidget", "class_progress_bar_widget.html", "class_progress_bar_widget" ],
    [ "RadioControlWidget", "class_radio_control_widget.html", "class_radio_control_widget" ],
    [ "SliderWidget", "class_slider_widget.html", "class_slider_widget" ],
    [ "Widget", "class_widget.html", "class_widget" ],
    [ "WidgetApplication", "class_widget_application.html", "class_widget_application" ],
    [ "WindowWidget", "class_window_widget.html", "class_window_widget" ]
];